id = "chai-theme"
name = "Chai Theme"
version = "0.0.2"
schema_version = 1
authors = ["Rushabh Patil <rushabhpatil.dev@gmail.com>"]
description = "Chai Theme for Zed"
repository = "https://github.com/rushabhcodes/zed-chai-theme"
